// web/src/lib/views/windows/IframeAppComponent.svelte
<script lang="ts">
  import { onMount, onDestroy, untrack } from 'svelte'
  import { connectionStore } from '$lib/stores/connectionStore.svelte'
  import { notificationsStore } from '$lib/stores/notificationsStore.svelte'
  import { settingsStore } from '$lib/stores/settingsStore.svelte'
  import { laptopStore } from '$lib/stores/laptopStore.svelte'
  import { parentResourceName } from '$lib/utils/parentResource.utils'
  import { fetchApi } from '$lib/utils/api'
  import { settingsBus, networkBus } from '$lib/utils/eventBus'
  import { onNuiEvent } from '$lib/utils/nuiEvent'
  import type { AppMessage, ExternalApp } from '$lib/types/app.types'

  import { appsStore } from '$lib/stores/appsStore.svelte'

  let { app, metadata, appReady, changeWindowTitle }: {
    app: ExternalApp
    metadata?: Record<string, any>
    appReady: () => void
    changeWindowTitle: (newTitle: string) => void
  } = $props()

  let appWindow = $derived(appsStore.windows[app.id])

  let iframeEl = $state<HTMLIFrameElement | null>(null)
  let ready = false
  const cleanups: (() => void)[] = []

  function postMessage(data: any) {
    iframeEl?.contentWindow?.postMessage(data, '*')
  }

  function iframeStyles() {
    if (!iframeEl) return
    const styles = 'visibility: visible; width: 100%; height: 100%; padding: 0; margin: 0;'
    iframeEl.contentDocument?.documentElement.setAttribute('style', styles)
    iframeEl.contentDocument?.body.setAttribute('style', styles)
  }

  async function markAsReady() {
    if (!iframeEl || ready) return
    ready = true

    if (app.onUseServer) {
      await fetchApi<null>('appOpened', { method: 'POST', body: JSON.stringify({ id: app.id }) }, null)
    }

    postMessage({ action: 'onOpen', data: {} })
    appReady()
    iframeStyles()
  }

  function detectAndAwaitFramework() {
    if (!iframeEl) return

    if (app.isAlpine) {
      awaitForAlpine()
    } else if (app.isReactOrVue) {
      awaitForContent()
    } else {
      setTimeout(markAsReady, 1000)
    }
  }

  function awaitForAlpine() {
    if (!iframeEl) return

    let retries = 0
    const MAX_RETRIES = 50

    const check = () => {
      if ((iframeEl!.contentWindow as any)?.Alpine) {
        return markAsReady()
      }
      if (++retries < MAX_RETRIES) {
        setTimeout(check, 100)
      } else {
        console.warn(`Alpine.js not detected after ${MAX_RETRIES} retries for app: ${app.id}`)
        markAsReady()
      }
    }

    check()
  }

  function awaitForContent() {
    if (!iframeEl) return

    try {
      const iframeDoc = iframeEl.contentDocument || iframeEl.contentWindow!.document

      const observer = new MutationObserver((mutations) => {
        for (const mutation of mutations) {
          if (mutation.addedNodes.length > 0) {
            markAsReady()
            observer.disconnect()
            return
          }
        }
      })

      observer.observe(iframeDoc.body, { childList: true, subtree: true })
    } catch (e) {
      console.error('Error while loading external app:', e)
    }
  }

  function setupIframeEvents() {
    if (!iframeEl) return

    const childEvents: Record<string, (data?: any) => void> = {
      appReady: () => markAsReady(),
      changeWindowTitle: (newTitle: string) => changeWindowTitle(newTitle),
      getAppData: () => postMessage({ action: `${app.id}:appData`, data: JSON.stringify(app) }),
      getSettings: () => postMessage({ action: `${app.id}:settings`, data: settingsStore.forApps }),
      getNetworkSettings: () => postMessage({ action: `${app.id}:network`, data: connectionStore.forApps }),
      getDevices: () => postMessage({ action: `${app.id}:devices`, data: JSON.stringify(laptopStore.installedDevices) }),
      sendNotification: (data: { summary: string; detail: string }) => notificationsStore.show(data)
    }

    const handler = (event: MessageEvent) => {
      if (typeof event.data === 'string') {
        childEvents[event.data]?.(event.data)
        return
      }
      const { action, data } = event.data
      childEvents[action]?.(data)
    }

    iframeEl.contentWindow?.addEventListener('message', handler)
    cleanups.push(() => {
      try { iframeEl?.contentWindow?.removeEventListener('message', handler) } catch {}
    })
  }

  function injectScripts() {
    if (!iframeEl) return

    const head = iframeEl.contentWindow?.document.head
    if (!head) return

    const scripts: string[] = []

    if (app.overrides && Array.isArray(app.overrides)) {
      scripts.push(...app.overrides)
    }

    scripts.push(`https://cfx-nui-${parentResourceName}/web/dist/global.js`)

    for (const src of scripts) {
      const script = document.createElement('script')
      script.setAttribute('src', src)
      head.prepend(script)
    }

    const globalDefinition = document.createElement('script')
    globalDefinition.appendChild(
      document.createTextNode(`
        globalThis.resourceName = '${app.resourceName}'
        globalThis.appId = '${app.id}'
      `)
    )
    head.prepend(globalDefinition)
  }

  function attachKeyupHandler() {
    if (!iframeEl) return

    const keyupHandler = (e: KeyboardEvent) => {
      if (e.key === 'Escape' && laptopStore.isOpen) {
        laptopStore.close(true)
      }
    }

    try {
      iframeEl.contentWindow?.addEventListener('keyup', keyupHandler)
      cleanups.push(() => {
        try { iframeEl?.contentWindow?.removeEventListener('keyup', keyupHandler) } catch {}
      })
    } catch {}
  }

  function iframeLoaded() {
    if (!iframeEl) return

    injectScripts()
    setupIframeEvents()
    attachKeyupHandler()
    detectAndAwaitFramework()
  }

  $effect(() => {
    const hidden = appWindow?.isHidden
    if (hidden === undefined) return

    untrack(() => {
      if (hidden) {
        if (app.onCloseServer) {
          fetchApi<null>('appClosed', { method: 'POST', body: JSON.stringify({ id: app.id }) }, null)
        }
        postMessage({ action: 'closeApp' })
      } else if (ready) {
        if (app.onUseServer) {
          fetchApi<null>('appOpened', { method: 'POST', body: JSON.stringify({ id: app.id }) }, null)
        }
        postMessage({ action: 'onOpen', data: {} })
      }
    })
  })

  onMount(() => {
    const unsubSettings = settingsBus.on((event) => {
      if (event !== 'updated') return
      postMessage({ action: 'changedSettings', data: settingsStore.forApps })
    })
    cleanups.push(unsubSettings)

    const unsubNetwork = networkBus.on((event) => {
      if (event !== 'updated') return
      postMessage({ action: 'networkChanged', data: connectionStore.forApps })
    })
    cleanups.push(unsubNetwork)

    const unsubNui = onNuiEvent<AppMessage>('sendAppMessage', (data) => {
      if (data.id !== app.id) return
      postMessage(data.message)
    })
    cleanups.push(unsubNui)
  })

  onDestroy(async () => {
    for (const cleanup of cleanups) cleanup()

    postMessage({ action: 'closeApp' })

    if (app.onCloseServer) {
      await fetchApi<null>('appClosed', { method: 'POST', body: JSON.stringify({ id: app.id }) }, null)
    }
  })
</script>

<iframe
  bind:this={iframeEl}
  src={app.ui}
  title={app.id}
  onload={iframeLoaded}
  name={app.id}
  class="flex flex-1 overflow-hidden"
></iframe>

// web/src/components/windows/IframeAppComponent.vue
<script setup lang="ts">
import type { InternalAppWindowBinds } from '../../types/window.types'
import { useConnection } from '../../stores/connection.store'
import { useNotifications } from '../../stores/notifications.store'
import { useSettings } from '../../stores/settings.store'
import { onKeyUp, useEventBus, useEventListener } from '@vueuse/core'
import { onBeforeUnmount, onMounted, useTemplateRef, type CSSProperties } from 'vue'
import type { AppMessage, ExternalApp } from '../../types/app.types'
import { parentResourceName } from '../../utils/parentResource.utils'
import { useLaptop } from '../../stores/laptop.store'
import { useNuiEvent } from '../../composables/useNuiEvent'
import { useApi } from '../../composables/useApi'

const props = defineProps<InternalAppWindowBinds<ExternalApp>>()

const laptop = useLaptop()
const settings = useSettings()
const notyf = useNotifications()
const connection = useConnection()
const settingsBus = useEventBus('settings')
const networkBus = useEventBus('network')

const iframe = useTemplateRef<HTMLIFrameElement>('iframe')

const postMessage = (data: any) => {
  if (!iframe.value) return

  iframe.value.contentWindow?.postMessage(data, '*')
}

const getAppData = () => {
  if (!iframe.value) return

  postMessage({
    action: `${props.app.id}:appData`,
    data: JSON.stringify(props.app)
  })
}

const getSettings = () => {
  if (!iframe.value) return

  postMessage({
    action: `${props.app.id}:settings`,
    data: settings.forApps
  })
}

const getNetworkSettings = () => {
  if (!iframe.value) return

  postMessage({
    action: `${props.app.id}:network`,
    data: connection.forApps
  })
}

const getInstalledDevices = () => {
  if (!iframe.value) return

  postMessage({
    action: `${props.app.id}:devices`,
    data: JSON.stringify(laptop.installedDevices)
  })
}

const sendNotification = (data: { summary: string; detail: string }) => {
  if (!iframe.value) return

  notyf.show(data)
}

const iframeStyles = () => {
  if (!iframe.value) return

  const styles: CSSProperties = {
    visibility: 'visible',
    width: `100%`,
    height: `100%`,
    padding: 0,
    margin: 0
  }

  const concentrated = Object.entries(styles)
    .map(([key, value]) => `${key}: ${value};`)
    .join(' ')

  iframe.value.contentDocument?.documentElement.setAttribute('style', concentrated)
  iframe.value.contentDocument?.body.setAttribute('style', concentrated)
}

const markAsReady = async () => {
  if (!iframe.value) return

  if (props.app.onUse || props.app.onUseServer) {
    await useApi<null>(
      'appOpened',
      {
        method: 'POST',
        body: JSON.stringify({ id: props.app.id })
      },
      undefined,
      null
    )
  }

  childComponentsLoaded()

  postMessage({
    action: 'onOpen',
    data: {}
  })

  props.appReady()
  iframeStyles()
}

const iframeEvents = () => {
  if (!iframe.value) return

  const childEvents: Record<string, (data?: any) => void> = {
    appReady: () => markAsReady(),
    changeWindowTitle: (newTitle: string) => props.changeWindowTitle(newTitle),
    getAppData: () => getAppData(),
    getSettings: () => getSettings(),
    getNetworkSettings: () => getNetworkSettings(),
    getDevices: () => getInstalledDevices(),
    sendNotification: (data: { summary: string; detail: string }) => sendNotification(data)
  }

  useEventListener(iframe.value.contentWindow!, 'message', (event: MessageEvent) => {
    if (typeof event.data === 'string') {
      if (!childEvents[event.data]) return

      return childEvents[event.data](event.data)
    }

    const { action, data } = event.data

    if (!childEvents[action]) return

    childEvents[action](data)
  })
}

const iframeBindings = () => {
  if (!iframe.value) return

  const body = iframe.value.contentWindow?.document.head
  if (!body) return

  if (props.app.overrides && Array.isArray(props.app.overrides)) {
    props.app.overrides.forEach((override) => {
      const script = document.createElement('script')
      script.setAttribute('src', override)
      body.prepend(script)
    })
  }

  const globalScript = document.createElement('script')
  globalScript?.setAttribute('src', `https://cfx-nui-${parentResourceName}/web/dist/global.js`)
  body?.prepend(globalScript)

  const globalDefinition = document.createElement('script')
  globalDefinition.appendChild(
    document.createTextNode(`
        globalThis.resourceName = '${props.app.resourceName}'
        globalThis.appId = '${props.app.id}'
    `)
  )
  body?.prepend(globalDefinition)
}

const awaitForContent = () => {
  if (!iframe.value) return

  try {
    iframe.value!.contentWindow?.postMessage(
      {
        action: 'showMenu'
      },
      '*'
    )

    const iframeDoc = iframe.value.contentDocument || iframe.value.contentWindow!.document

    const observer = new MutationObserver(async (mutations) => {
      let hasContent = false
      mutations.forEach((mutation) => {
        if (mutation.addedNodes.length > 0) {
          hasContent = true
        }
      })

      if (hasContent) {
        markAsReady()

        observer.disconnect()
      }
    })

    observer.observe(iframeDoc.body, {
      childList: true,
      subtree: true
    })
  } catch (e) {
    console.error('Error while loading external app:', e)
  }
}

const awaitForAlpineToLoad = () => {
  if (!iframe.value) return

  const checkAlpine = () => {
    //@ts-ignore
    if (iframe.value!.contentWindow?.Alpine) {
      markAsReady()
      return
    }

    setTimeout(checkAlpine, 100)
  }

  checkAlpine()
}

const iframeLoaded = () => {
  if (!iframe.value) return

  if (props.app.ui.includes('rahe-') || props.app.ui.includes('kub-') || props.app.isAlpine) {
    awaitForAlpineToLoad()
  } else if (props.app.isReactOrVue) {
    awaitForContent()
  } else {
    setTimeout(markAsReady, 1000)
  }

  iframeEvents()
  iframeBindings()
}

const childComponentsLoaded = () => {
  if (props.app.ui.includes('rahe-')) {
    raheOverrides()
  }

  if (props.app.ui.includes('kub_')) {
    kubOverrides()
  }
}

const kubOverrides = (show: boolean = true) => {
  iframe.value!.contentWindow?.postMessage(
    {
      type: show ? 'showUI' : 'hideUI'
    },
    '*'
  )

  if (show) {
    const body = iframe.value!.contentWindow?.document.body!

    body.firstElementChild?.setAttribute(
      'style',
      'position:relative; margin: 0; left: 0; top: 0; width: 100%; height: 100%; max-height: auto; max-width: auto; transform: none;'
    )

    const head = iframe.value!.contentWindow?.document.head!
    const style = head.appendChild(document.createElement('style'))
    style.setAttribute('type', 'text/css')
    style.appendChild(
      document.createTextNode(
        '.border-image { border-image: unset !important; } .ipad{border: unset !important;} .ipad::after{display:none !important;}'
      )
    )
  }
}

const raheOverrides = (show: boolean = true) => {
  iframe.value!.contentWindow?.postMessage(
    {
      action: show ? 'showMenu' : 'hideMenu'
    },
    '*'
  )

  if (show) {
    const body = iframe.value!.contentWindow?.document.body!

    body.firstElementChild?.setAttribute(
      'style',
      'position:relative; margin: 0; left: 0; top: 0; width: 100%; height: 100%;'
    )

    body.getElementsByClassName('tablet-frame')[0]?.remove()
  }
}

onMounted(async () => {
  settingsBus.on((event) => {
    if (event !== 'updated') return

    iframe.value!.contentWindow?.postMessage(
      {
        action: `changedSettings`,
        data: settings.forApps
      },
      '*'
    )
  })

  networkBus.on((event) => {
    if (event !== 'updated') return

    iframe.value!.contentWindow?.postMessage(
      {
        action: `networkChanged`,
        data: connection.forApps
      },
      '*'
    )
  })

  onKeyUp(
    'Escape',
    () => {
      if (!laptop.isOpen) return

      laptop.close(true)
    },
    {
      target: iframe.value!.contentWindow?.window
    }
  )
})

useNuiEvent<AppMessage>('sendAppMessage', (data: AppMessage) => {
  if (data.id !== props.app.id) return

  postMessage(data.message)
})

onBeforeUnmount(async () => {
  if (props.app.ui.includes('rahe-')) {
    raheOverrides(false)
  }

  if (props.app.ui.includes('kub-')) {
    kubOverrides(false)
  }

  postMessage({
    action: 'closeApp'
  })

  if (props.app.onClose || props.app.onCloseServer) {
    await useApi<null>(
      'appClosed',
      {
        method: 'POST',
        body: JSON.stringify({ id: props.app.id })
      },
      undefined,
      null
    )
  }
})
</script>
<template>
  <iframe
    ref="iframe"
    :src="(app as ExternalApp).ui"
    :frame-id="app.id"
    :onload="iframeLoaded"
    :name="app.id"
  ></iframe>
</template>
