// web/src/lib/views/taskbar/ActiveApps.svelte
<script lang="ts">
  import { appsStore } from '$lib/stores/appsStore.svelte'
  import ActiveAppButton from './ActiveAppButton.svelte'

  function toggleStates(id: string) {
    const window = appsStore.windows[id]

    if (window.state.isMinimized) {
      appsStore.toggleMinimizeState(id, false)
      appsStore.toggleActiveState(id, true)
      return
    }

    if (!window.state.isActive) {
      appsStore.toggleActiveState(id, true)
      return
    }

    appsStore.toggleActiveState(id, false)
    appsStore.toggleMinimizeState(id, true)
  }
</script>

<div class="z-10 flex flex-1 gap-1 py-1">
  {#each appsStore.shownWindows as appWindow (appWindow.app.id)}
    <ActiveAppButton
      windowState={appWindow.state}
      id={appWindow.app.id}
      icon={appWindow.app.icon}
      name={appWindow.app.name}
      isActive={appWindow.state.isActive && !appWindow.state.isMinimized}
      onclick={() => toggleStates(appWindow.app.id)}
    />
  {/each}
</div>

// web/src/components/taskbar/ActiveApps.vue
<script setup lang="ts">
import { defineAsyncComponent } from 'vue'
import { useApplications } from '../../stores/apps.store'

const apps = useApplications()
const ActiveAppButton = defineAsyncComponent(() => import('./ActiveAppButton.vue'))

const toggleStates = (id: string) => {
  if (!apps.windows[id].state.isMinimized) {
    apps.toggleActiveState(id, false)
    apps.toggleMinimizeState(id, true)

    return
  }

  apps.toggleActiveState(id, true)
  apps.toggleMinimizeState(id, false)
}
</script>
<template>
  <div class="z-10 flex flex-1 gap-1 py-1">
    <ActiveAppButton
      v-for="window in apps.shownWindows"
      v-tooltip.top="window.app.name"
      :key="window.app.id"
      :state="window.state"
      :id="window.app.id"
      :icon="window.app.icon"
      :isActive="window.state.isActive && !window.state.isMinimized"
      @click="toggleStates(window.app.id)"
    />
  </div>
</template>
