// web/src/lib/views/overlays/NotificationsOverlay.svelte
<script lang="ts">
  import { notificationsStore } from '$lib/stores/notificationsStore.svelte'
  import { appsStore } from '$lib/stores/appsStore.svelte'
  import { localeStore } from '$lib/stores/localeStore.svelte'
  import { fly } from 'svelte/transition'
  import NotificationItem from '$lib/components/NotificationItem.svelte'

  let { isOpen = false, onclose }: {
    isOpen?: boolean
    onclose?: () => void
  } = $props()

  function openSettings() {
    onclose?.()
    appsStore.open('settings', { tab: 'notifications' })
  }
</script>

{#if isOpen}
  <div
    id="notifications-area"
    class="fixed bottom-20 right-4 top-4 z-[999] flex w-96 transform flex-col rounded-2xl bg-[#1E2028] shadow-xl"
    transition:fly={{ x: 400, duration: 300 }}
  >
    <div class="flex flex-1 flex-col overflow-hidden">
      <div class="flex items-center justify-between px-5 py-4">
        <span class="text-base font-semibold text-gray-100">{localeStore.t('notifications_overlay_title')}</span>
        <button
          type="button"
          aria-label="Close"
          class="flex h-7 w-7 items-center justify-center rounded-lg text-gray-400 transition-colors hover:bg-gray-700/80 hover:text-gray-100"
          onclick={onclose}
        >
          <i class="fa-solid fa-xmark text-xs"></i>
        </button>
      </div>
      <div
        class="flex-1 space-y-2 overflow-y-auto px-4 pb-2 scrollbar-thin scrollbar-track-rounded-[100px] scrollbar-thumb-rounded-[100px] scrollbar-corner-rounded-[100px] scrollbar-track-gray-500/80 scrollbar-thumb-gray-400/80"
      >
        {#each notificationsStore.notifications as notification, index}
          <NotificationItem
            summary={notification.summary}
            detail={notification.detail}
            timestamp={notification.time}
            variant="overlay"
            onclose={() => notificationsStore.close(index)}
          />
        {/each}
      </div>
      <div class="flex justify-between border-t border-gray-700/50 px-2 py-2">
        <button
          type="button"
          class="rounded-lg px-3 py-1.5 text-[13px] font-medium text-[#7C8AED] transition-colors hover:bg-[#7C8AED]/10"
          onclick={openSettings}
        >
          {localeStore.t('notifications_overlay_settings_button')}
        </button>
        <button
          type="button"
          class="rounded-lg px-3 py-1.5 text-[13px] font-medium text-[#7C8AED] transition-colors hover:bg-[#7C8AED]/10"
          onclick={() => notificationsStore.clear()}
        >
          {localeStore.t('notifications_overlay_clear_button')}
        </button>
      </div>
    </div>
  </div>
{/if}

// web/src/components/overlays/NotificationsOverlay.vue
<script setup lang="ts">
import { useNotifications } from '../../stores/notifications.store'
import { onClickOutside, useTimeAgo } from '@vueuse/core'
import { ref } from 'vue'
//@ts-ignore
import Toast from '../../services/toast/Toast.vue'
import { useApplications } from '../../stores/apps.store'
import Button from 'primevue/button'
import { useLocale } from '../../stores/locale.store'

defineProps({
  isOpen: {
    type: Boolean,
    default: false
  }
})

const locale = useLocale()
const apps = useApplications()
const notif = useNotifications()

const overlay = ref<HTMLDivElement>()
const emit = defineEmits(['close'])

onClickOutside(overlay, () => {
  emit('close')
})

const openSettings = () => {
  emit('close')
  apps.open('settings', { tab: 'notifications' })
}
</script>
<template>
  <Teleport to="#laptop" defer>
    <Toast position="bottom-right" group="headless" to="#laptop" v-show="!isOpen">
      <template #container="{ message, closeCallback }">
        <div
          class="block space-y-1 rounded bg-white/50 p-3 text-sm backdrop-blur-xl hover:bg-white/25 active:bg-white/50 dark:bg-black/30 dark:hover:bg-black/50 dark:active:bg-black/30"
        >
          <div class="flex items-center justify-between">
            <h3 class="font-medium">{{ message.summary }}</h3>
            <Button
              icon="pi pi-times"
              size="small"
              rounded
              outlined
              aria-label="Close"
              @click.prevent="closeCallback"
            />
          </div>
          <p class="leading-5 text-gray-700 dark:text-gray-400">
            {{ message.detail }}
          </p>
        </div>
      </template>
    </Toast>
  </Teleport>
  <Teleport to="#laptop" defer>
    <div
      v-show="isOpen"
      ref="overlay"
      id="notifications-area"
      class="absolute bottom-0 right-0 top-0 z-[999] flex w-96 transform flex-col bg-gray-100/60 backdrop-blur-xl dark:bg-gray-800/60"
    >
      <div class="flex flex-1 flex-col overflow-hidden pr-2">
        <div class="flex items-center justify-between py-4 pl-4">
          <span class="text-lg font-semibold">{{ locale.t('notifications_overlay_title') }}</span>
          <Button
            icon="pi pi-times"
            aria-label="Close"
            size="small"
            link
            @click.prevent="emit('close')"
          />
        </div>
        <div
          class="flex-1 space-y-2 overflow-y-auto px-4 scrollbar-thin scrollbar-track-rounded-[100px] scrollbar-thumb-rounded-[100px] scrollbar-corner-rounded-[100px] dark:scrollbar-track-gray-500/80 dark:scrollbar-thumb-gray-400/80"
        >
          <div
            class="block space-y-1 rounded bg-white/50 p-3 text-sm hover:bg-white/25 active:bg-white/50 dark:bg-black/30 dark:hover:bg-black/50 dark:active:bg-black/30"
            v-for="(notification, index) in notif.notifications"
          >
            <div class="flex items-center justify-between">
              <h3 class="font-medium">{{ notification.summary }}</h3>
              <Button
                icon="pi pi-times"
                size="small"
                rounded
                outlined
                aria-label="Close"
                @click.prevent="notif.close(index)"
              />
            </div>
            <p class="leading-5 text-gray-700 dark:text-gray-400">
              {{ notification.detail }}
            </p>
            <p class="text-gray-600 dark:text-gray-500">{{ useTimeAgo(notification.time) }}</p>
          </div>
        </div>
        <div class="flex justify-between">
          <Button
            :label="locale.t('notifications_overlay_settings_button')"
            @click.prevent="openSettings()"
            link
            size="small"
          />

          <Button
            :label="locale.t('notifications_overlay_clear_button')"
            @click.prevent="notif.clear()"
            link
            size="small"
          />
        </div>
      </div>
    </div>
  </Teleport>
</template>
