// web/src/App.vue
<script setup lang="ts">
import { defineAsyncComponent, onMounted } from 'vue'
import { useDevelopment } from './stores/development.store'
import { useLaptop } from './stores/laptop.store'
import { useNotifications } from './stores/notifications.store'

const Laptop = defineAsyncComponent(() => import('./components/Laptop.vue'))
const DevelopmentToolbar = defineAsyncComponent(
  () => import('./devComponents/DevelopmentToolbar.vue')
)

const dev = useDevelopment()
const laptop = useLaptop()
const notif = useNotifications()

onMounted(() => {
  if (dev.isDevEnv) {
    dev.applyDevelopmentStyles()
  }

  laptop.init()
})
</script>

<template>
  <Laptop v-show="laptop.isOpen || notif.shouldBeShown" />
  <DevelopmentToolbar v-if="dev.isDevEnv" />
</template>

// web/src/App.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { developmentStore } from '$lib/stores/developmentStore.svelte'
  import { laptopStore } from '$lib/stores/laptopStore.svelte'
  import { notificationsStore } from '$lib/stores/notificationsStore.svelte'
  import { settingsStore } from '$lib/stores/settingsStore.svelte'
  import Laptop from '$lib/views/Laptop.svelte'
  import DevelopmentToolbar from '$lib/devComponents/DevelopmentToolbar.svelte'

  let showLaptop = $derived(laptopStore.isOpen || notificationsStore.shouldBeShown(laptopStore.isOpen, settingsStore.doNotDisturb))

  onMount(() => {
    if (developmentStore.isDevEnv) {
      developmentStore.applyDevelopmentStyles()
    }

    laptopStore.init()
  })
</script>

<div class={showLaptop ? '' : 'hidden'}>
  <Laptop />
</div>
{#if developmentStore.isDevEnv}
  <DevelopmentToolbar />
{/if}
