// web/src/apps/settings/BackgroundTab.vue
<script setup lang="ts">
import type { AvailableBackground } from '../../types/background.types'
import type { InternalAppWindowBinds } from '../../types/window.types'
import { useApi } from '../../composables/useApi'
import { MockedBackgrounds } from '../../mock/backgrounds.mock'
import { useSettings } from '../../stores/settings.store'
import { onMounted, onUnmounted, ref } from 'vue'
import { useNotifications } from '../../stores/notifications.store'
import { useEventBus } from '@vueuse/core'
import { backgroundUrl } from '../../utils/url.utils'
import Button from 'primevue/button'
import Skeleton from 'primevue/skeleton'
import { useLocale } from '../../stores/locale.store'

interface SavedBackgroundResponse {
  success: boolean
  error?: string
}

const props = defineProps<Omit<InternalAppWindowBinds, 'appReady' | 'app'>>()

const settings = useSettings()
const locale = useLocale()
const notif = useNotifications()
const bus = useEventBus('settings')

const isLoading = ref<boolean>(true)
const isChanging = ref<boolean>(false)
const backgrounds = ref<AvailableBackground[]>([])
const originalBackground = ref<string>()

onMounted(async () => {
  props.changeWindowTitle(locale.t('settings_background_title'))

  const { data } = await useApi<AvailableBackground[]>(
    `availableBackgrounds`,
    {},
    undefined,
    MockedBackgrounds
  )

  if (!data.value) {
    return
  }

  backgrounds.value = data.value

  isLoading.value = false
})

const resetBackground = () => {
  if (isChanging.value) return

  if (!originalBackground.value) {
    return
  }

  changeBackground(originalBackground.value)
}

const changeBackground = (background: string) => {
  if (isChanging.value) return

  if (!originalBackground.value) {
    originalBackground.value = settings.backgroundImage
  }

  if (originalBackground.value === background) {
    originalBackground.value = undefined
  }

  settings.changeBackground(background)
}

const saveBackground = async () => {
  if (isChanging.value) return
  if (!originalBackground.value) return

  const { data } = await useApi<SavedBackgroundResponse>(
    'saveBackground',
    {
      method: 'POST',
      body: JSON.stringify({ background: settings.backgroundImage })
    },
    undefined,
    {
      success: true,
      error: undefined
    }
  )

  const { success } = data.value as SavedBackgroundResponse

  if (!success) {
    notif.show({
      summary: locale.t('settings_background_saving_error_title'),
      detail: locale.t('settings_background_saving_error_description')
    })

    resetBackground()
    return
  }

  notif.show({
    summary: locale.t('settings_background_saving_success_title'),
    detail: locale.t('settings_background_saving_success_description')
  })

  bus.emit('updated')

  originalBackground.value = undefined
}

onUnmounted(() => {
  resetBackground()
})
</script>
<template>
  <div v-if="isLoading" class="lscrollbar mb-2 grid auto-rows-[9rem] grid-cols-3 gap-4">
    <Skeleton height="9rem"></Skeleton>
    <Skeleton height="9rem"></Skeleton>
    <Skeleton height="9rem"></Skeleton>
    <Skeleton height="9rem"></Skeleton>
    <Skeleton height="9rem"></Skeleton>
    <Skeleton height="9rem"></Skeleton>
    <Skeleton height="9rem"></Skeleton>
    <Skeleton height="9rem"></Skeleton>
    <Skeleton height="9rem"></Skeleton>
  </div>
  <div v-else class="lscrollbar grid auto-rows-[9rem] grid-cols-3 gap-4 overflow-auto">
    <div
      class="after:content[''] after:height-[9rem] relative col-span-1 aspect-square overflow-hidden rounded-lg after:relative after:w-full hover:cursor-pointer"
      v-for="bg in backgrounds"
      :key="bg.src"
      @click.prevent="changeBackground(bg.src)"
    >
      <div
        class="absolute inset-0 border-4 border-blue-500"
        v-if="settings.backgroundImage === bg.src"
      >
        <div class="absolute bottom-0 right-0 rounded-tl-lg bg-blue-500 pl-2 pr-1 pt-1">
          <div class="flex items-center justify-between gap-2" v-if="originalBackground">
            <Button icon="pi pi-save" @click.stop="saveBackground()" size="small" />
            <Button
              icon="pi pi-refresh"
              @click.stop="resetBackground()"
              severity="secondary"
              size="small"
            />
          </div>
          <i v-else class="pi pi-check text-xs"></i>
        </div>
      </div>
      <img :src="backgroundUrl(bg.src)" alt="" class="h-full w-full object-cover" v-memo="bg.src" />
    </div>
  </div>
</template>

// web/src/apps/settings/BackgroundTab.svelte
<script lang="ts">
  import { onMount, onDestroy } from 'svelte'
  import type { AvailableBackground } from '$lib/types/background.types'
  import { fetchApi } from '$lib/utils/api'
  import { MockedBackgrounds } from '../../mock/backgrounds.mock'
  import { settingsStore } from '$lib/stores/settingsStore.svelte'
  import { notificationsStore } from '$lib/stores/notificationsStore.svelte'
  import { localeStore } from '$lib/stores/localeStore.svelte'
  import { settingsBus } from '$lib/utils/eventBus'
  import { backgroundUrl } from '$lib/utils/url.utils'
  import Skeleton from '$lib/components/Skeleton.svelte'

  interface SavedBackgroundResponse {
    success: boolean
    error?: string
  }

  let { changeWindowTitle }: {
    changeWindowTitle: (newTitle: string) => void
  } = $props()

  let isLoading = $state(true)
  let isChanging = $state(false)
  let backgrounds = $state<AvailableBackground[]>([])
  let originalBackground = $state<string | undefined>()

  onMount(async () => {
    changeWindowTitle(localeStore.t('settings_background_title'))

    const data = await fetchApi<AvailableBackground[]>(
      'availableBackgrounds',
      {},
      MockedBackgrounds
    )

    if (!data) return

    backgrounds = data
    isLoading = false
  })

  function resetBackground() {
    if (isChanging) return
    if (!originalBackground) return

    changeBackground(originalBackground)
  }

  function changeBackground(background: string) {
    if (isChanging) return

    if (!originalBackground) {
      originalBackground = settingsStore.backgroundImage
    }

    if (originalBackground === background) {
      originalBackground = undefined
    }

    settingsStore.changeBackground(background)
  }

  async function saveBackground() {
    if (isChanging) return
    if (!originalBackground) return

    const data = await fetchApi<SavedBackgroundResponse>(
      'saveBackground',
      {
        method: 'POST',
        body: JSON.stringify({ background: settingsStore.backgroundImage })
      },
      { success: true, error: undefined }
    )

    const { success } = data as SavedBackgroundResponse

    if (!success) {
      notificationsStore.show({
        summary: localeStore.t('settings_background_saving_error_title'),
        detail: localeStore.t('settings_background_saving_error_description')
      })

      resetBackground()
      return
    }

    notificationsStore.show({
      summary: localeStore.t('settings_background_saving_success_title'),
      detail: localeStore.t('settings_background_saving_success_description')
    })

    settingsBus.emit('updated')

    originalBackground = undefined
  }

  onDestroy(() => {
    resetBackground()
  })
</script>

<div class="flex flex-1 flex-col gap-4 overflow-hidden">
  <div class="flex items-center justify-between">
    <h2 class="text-base font-semibold text-[#F0F0F5]">
      {localeStore.t('settings_background_tab_label')}
    </h2>
    {#if originalBackground}
      <div class="flex items-center gap-2">
        <button
          type="button"
          aria-label="Save background"
          class="flex h-8 w-8 items-center justify-center rounded-full bg-[#5BBD6B] text-white shadow-sm transition-colors hover:bg-[#4DAD5D]"
          onclick={() => saveBackground()}
        >
          <i class="fa-solid fa-floppy-disk text-xs"></i>
        </button>
        <button
          type="button"
          aria-label="Reset background"
          class="flex h-8 w-8 items-center justify-center rounded-full bg-[#2D2F3A] text-[#8B8D9A] shadow-sm transition-colors hover:bg-[#3a3c4a]"
          onclick={() => resetBackground()}
        >
          <i class="fa-solid fa-rotate text-xs"></i>
        </button>
      </div>
    {/if}
  </div>

  {#if isLoading}
    <div class="lscrollbar flex-1 min-h-0 overflow-y-auto overflow-x-hidden p-2">
      <div class="grid grid-cols-3 gap-3">
      {#each Array(9) as _}
        <div class="aspect-[5/4]">
          <Skeleton height="100%" />
        </div>
      {/each}
      </div>
    </div>
  {:else}
    <div class="lscrollbar flex-1 min-h-0 overflow-y-auto overflow-x-hidden p-2">
      <div class="grid grid-cols-3 gap-3">
      {#each backgrounds as bg (bg.src)}
        <!-- svelte-ignore a11y_click_events_have_key_events -->
        <!-- svelte-ignore a11y_no_static_element_interactions -->
        <div
          class="group relative cursor-pointer overflow-hidden rounded-xl {settingsStore.backgroundImage === bg.src ? 'ring-[3px] ring-[#7C8AED]' : ''}"
          onclick={() => changeBackground(bg.src)}
        >
          <img src={backgroundUrl(bg.src)} alt="" class="block aspect-[5/4] w-full object-cover" />
          {#if settingsStore.backgroundImage === bg.src && !originalBackground}
            <div class="absolute bottom-1.5 right-1.5 flex h-5 w-5 items-center justify-center rounded-full bg-[#7C8AED]">
              <i class="fa-solid fa-check text-[10px] text-white"></i>
            </div>
          {/if}
        </div>
      {/each}
      </div>
    </div>
  {/if}
</div>
