// web/src/apps/settings/ProfileTab.vue
<script setup lang="ts">
import type { InternalAppWindowBinds } from '../../types/window.types'
import { useForm } from 'vee-validate'
import { useSettings } from '../../stores/settings.store'
import { onMounted, ref } from 'vue'
import { toTypedSchema } from '@vee-validate/valibot'
import { nonEmpty, object, pipe, string, url } from 'valibot'
import { useApi } from '../../composables/useApi'
import { useNotifications } from '../../stores/notifications.store'
import { useEventBus } from '@vueuse/core'
import Avatar from 'primevue/avatar'
import Button from 'primevue/button'
import InputText from 'primevue/inputtext'
import type { ProfileUpdateResponse } from '../../types/profile.types'
import { useLocale } from '../../stores/locale.store'

const notif = useNotifications()
const settings = useSettings()
const locale = useLocale()
const props = defineProps<Omit<InternalAppWindowBinds, 'appReady' | 'app'>>()
const bus = useEventBus('settings')

const isLoading = ref<boolean>(false)

const { errors, defineField, handleSubmit, setFieldError, resetForm } = useForm({
  validationSchema: toTypedSchema(
    object({
      nickname: pipe(
        string(locale.t('settings_profile_nickname_a_string')),
        nonEmpty(locale.t('settings_profile_nickname_not_empty'))
      ),
      profilePicture: pipe(
        string(locale.t('settings_profile_profile_picture_a_string')),
        nonEmpty(locale.t('settings_profile_profile_picture_not_empty')),
        url(locale.t('settings_profile_profile_picture_valid_url'))
      )
    })
  ),
  initialValues: {
    nickname: settings.username,
    profilePicture: settings.profilePicture
  }
})

const [nickname] = defineField('nickname')
const [profilePicture] = defineField('profilePicture')

const saveProfile = handleSubmit(async (values) => {
  if (settings.username === values.nickname && settings.profilePicture === values.profilePicture) {
    return
  }

  isLoading.value = true

  const { data } = await useApi<ProfileUpdateResponse>(
    'updateUserSettings',
    {
      method: 'POST',
      body: JSON.stringify({
        nickname: values.nickname,
        profile_picture: values.profilePicture
      })
    },
    undefined,
    {
      success: true,
      error: undefined
    }
  )

  const { success, error } = data.value as ProfileUpdateResponse

  isLoading.value = false

  if (!success) {
    setFieldError('nickname', error)

    return
  }

  notif.show({
    summary: locale.t('settings_profile_updated_title'),
    detail: locale.t('settings_profile_updated_description')
  })

  bus.emit('updated')
})

onMounted(() => {
  props.changeWindowTitle(locale.t('settings_profile_title'))
})
</script>
<template>
  <div class="flex flex-1 flex-col items-center justify-center gap-5">
    <div class="flex flex-col items-center justify-between gap-3">
      <Avatar v-if="!settings.profilePicture" icon="pi pi-user" size="xlarge" class="border" />
      <Avatar v-else :image="settings.profilePicture" size="xlarge" />
      <span>
        {{ settings.username }}
      </span>
    </div>
    <div
      class="flex w-full flex-col items-center justify-between gap-10 rounded-lg bg-gray-300 p-4 dark:bg-gray-800"
    >
      <div class="flex w-full flex-col gap-3">
        <div class="flex w-full flex-col gap-1">
          <div class="flex items-center justify-between">
            <label for="nickname">{{ locale.t('settings_profile_nickname_field_label') }}</label>
            <a href="#" @click.prevent="resetForm()" v-tooltip.top="'Reset'">
              <i class="pi pi-refresh text-xs"></i>
            </a>
          </div>
          <InputText
            id="nickname"
            fluid
            aria-describedby="nickname-help"
            :placeholder="locale.t('settings_profile_nickname_field_placeholder')"
            v-model="nickname"
            :invalid="!!errors.nickname"
          />
          <small class="text-red-200" v-show="errors.nickname" v-text="errors.nickname"></small>
        </div>
        <div class="flex w-full flex-col gap-1">
          <label for="profileUrl">
            {{ locale.t('settings_profile_profile_picture_field_label') }}
          </label>
          <InputText
            id="profilePicture"
            fluid
            aria-describedby="profile-picture-url"
            :placeholder="locale.t('settings_profile_profile_picture_field_placeholder')"
            v-model="profilePicture"
            :invalid="!!errors.profilePicture"
          />
          <small
            class="text-red-200"
            v-show="errors.profilePicture"
            v-text="errors.profilePicture"
          ></small>
        </div>
      </div>
      <Button
        @click.prevent="saveProfile"
        :label="locale.t('settings_profile_save_button')"
        fluid
        :loading="isLoading"
        :disabled="
          isLoading ||
          (settings.username === nickname && settings.profilePicture === profilePicture)
        "
      />
    </div>
  </div>
</template>

// web/src/apps/settings/ProfileTab.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { settingsStore } from '$lib/stores/settingsStore.svelte'
  import { notificationsStore } from '$lib/stores/notificationsStore.svelte'
  import { localeStore } from '$lib/stores/localeStore.svelte'
  import { fetchApi } from '$lib/utils/api'
  import { settingsBus } from '$lib/utils/eventBus'
  import { nonEmpty, object, pipe, string, url, safeParse } from 'valibot'
  import type { ProfileUpdateResponse } from '$lib/types/profile.types'
  import Avatar from '$lib/components/Avatar.svelte'

  let { changeWindowTitle }: {
    changeWindowTitle: (newTitle: string) => void
  } = $props()

  let isLoading = $state(false)
  let nickname = $state(settingsStore.username)
  let profilePicture = $state(settingsStore.profilePicture || '')
  let errors = $state<Record<string, string>>({})

  const schema = object({
    nickname: pipe(
      string(localeStore.t('settings_profile_nickname_a_string')),
      nonEmpty(localeStore.t('settings_profile_nickname_not_empty'))
    ),
    profilePicture: pipe(
      string(localeStore.t('settings_profile_profile_picture_a_string')),
      nonEmpty(localeStore.t('settings_profile_profile_picture_not_empty')),
      url(localeStore.t('settings_profile_profile_picture_valid_url'))
    )
  })

  function resetForm() {
    nickname = settingsStore.username
    profilePicture = settingsStore.profilePicture || ''
    errors = {}
  }

  async function saveProfile() {
    errors = {}

    const result = safeParse(schema, { nickname, profilePicture })

    if (!result.success) {
      for (const issue of result.issues) {
        const path = issue.path?.[0]?.key
        if (path && typeof path === 'string') {
          errors[path] = issue.message
        }
      }
      return
    }

    if (settingsStore.username === nickname && settingsStore.profilePicture === profilePicture) {
      return
    }

    isLoading = true

    const data = await fetchApi<ProfileUpdateResponse>(
      'updateUserSettings',
      {
        method: 'POST',
        body: JSON.stringify({
          nickname,
          profile_picture: profilePicture
        })
      },
      { success: true, error: undefined }
    )

    const { success, error } = data as ProfileUpdateResponse

    isLoading = false

    if (!success) {
      errors = { nickname: error || 'Error' }
      return
    }

    notificationsStore.show({
      summary: localeStore.t('settings_profile_updated_title'),
      detail: localeStore.t('settings_profile_updated_description')
    })

    settingsBus.emit('updated')
  }

  let isUnchanged = $derived(
    settingsStore.username === nickname && settingsStore.profilePicture === profilePicture
  )

  onMount(() => {
    changeWindowTitle(localeStore.t('settings_profile_title'))
  })
</script>

<div class="flex flex-1 flex-col gap-4 overflow-auto">
  <h2 class="text-base font-semibold text-[#F0F0F5]">
    {localeStore.t('settings_profile_tab_label')}
  </h2>

  <div class="flex items-center gap-4 rounded-xl bg-[#1E2028] px-4 py-4">
    <Avatar
      image={settingsStore.profilePicture}
      icon={settingsStore.profilePicture ? undefined : 'fa-solid fa-user'}
      size="xlarge"
    />
    <div class="flex flex-col">
      <span class="text-sm font-semibold text-[#F0F0F5]">{settingsStore.username}</span>
      {#if settingsStore.job}
        <span class="text-xs text-[#8B8D9A]">{settingsStore.job}</span>
      {/if}
    </div>
  </div>

  <div class="rounded-xl bg-[#1E2028] p-4">
    <div class="mb-3 flex items-center justify-between">
      <span class="text-xs font-medium uppercase tracking-wide text-[#8B8D9A]">
        {localeStore.t('settings_profile_tab_label')}
      </span>
      <button type="button" aria-label="Reset" onclick={resetForm} class="text-xs text-[#8B8D9A] transition-colors hover:text-[#F0F0F5]">
        <i class="fa-solid fa-rotate text-xs"></i>
      </button>
    </div>

    <div class="flex flex-col gap-3">
      <div class="flex flex-col gap-1">
        <label for="nickname" class="text-xs font-medium text-[#8B8D9A]">
          {localeStore.t('settings_profile_nickname_field_label')}
        </label>
        <input
          id="nickname"
          bind:value={nickname}
          placeholder={localeStore.t('settings_profile_nickname_field_placeholder')}
          class="w-full rounded-lg border bg-[#16171C] px-3 py-2 text-sm text-[#F0F0F5] outline-none transition-colors focus:border-[#7C8AED] {errors.nickname ? 'border-[#E55B5B]' : 'border-[#2D2F3A]'}"
        />
        {#if errors.nickname}
          <small class="text-[#E55B5B]">{errors.nickname}</small>
        {/if}
      </div>
      <div class="flex flex-col gap-1">
        <label for="profilePicture" class="text-xs font-medium text-[#8B8D9A]">
          {localeStore.t('settings_profile_profile_picture_field_label')}
        </label>
        <input
          id="profilePicture"
          bind:value={profilePicture}
          placeholder={localeStore.t('settings_profile_profile_picture_field_placeholder')}
          class="w-full rounded-lg border bg-[#16171C] px-3 py-2 text-sm text-[#F0F0F5] outline-none transition-colors focus:border-[#7C8AED] {errors.profilePicture ? 'border-[#E55B5B]' : 'border-[#2D2F3A]'}"
        />
        {#if errors.profilePicture}
          <small class="text-[#E55B5B]">{errors.profilePicture}</small>
        {/if}
      </div>
    </div>

    <button
      type="button"
      class="mt-4 w-full rounded-lg bg-[#5BBD6B] px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-[#4DAD5D] disabled:opacity-50"
      onclick={saveProfile}
      disabled={isLoading || isUnchanged}
    >
      {#if isLoading}
        <i class="fa-solid fa-spinner fa-spin"></i>
      {:else}
        {localeStore.t('settings_profile_save_button')}
      {/if}
    </button>
  </div>
</div>
